FeetClinic.WEB/Models/TreatmentViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeetClinic.WEB.Models
{
    public class TreatmentCreateViewModel
    {
        [Display(Name = "Treatment Type")]
        [Required(ErrorMessage = "Choose type for treatment")]
        public int SelectedTypeId { get; set; }
        public IEnumerable<SelectListItem> Types { get; set; }

        [Display(Name = "Therapist")]
        [Required(ErrorMessage = "Choose therapists")]
        public int[] SelectedTherapistId { get; set; }
        public IEnumerable<SelectListItem> Therap { get; set; }

        [Required(ErrorMessage = "Enter the name for treatment")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
        [Required(ErrorMessage = "Enter the price for treatment")]
        [DataType(DataType.Currency)]
        public decimal Price { get; set; }
        [Required(ErrorMessage = "Enter duration i format tt:mm:ss")]
        public TimeSpan Duration { get; set; }
    }

    public class TreatmentEditViewModel : TreatmentCreateViewModel
    {
        [Key]
        public int Id { get; set; }
        
    }

}

FeetClinic.WEB/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BE.BE;
using BE.BE.Schedule;
using BE.BE.Treatments;
using BE.Interfaces;
using BE.Services;
using FeetClinic.WEB.Models;
using FeetClinic.WEB.ServiceGateway;

namespace FeetClinic.WEB.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        private ServiceGatewayFactory factory;

        public BookingController()
        {
            factory = new ServiceGatewayFactory();
        }

        [Authorize]
        // GET: Booking
        public ActionResult Index(int? userId)
        {
            if (userId == null)
            {
                userId = User.Identity.GetUserId<int>();
            }
            IEnumerable<Booking> bookings = factory.BookingGateway
                .GetForCustomer((int) userId, "Treatments,Therapist");
            return View(bookings);
        }

        // GET: Booking/Create
        public ActionResult Create(int? therapistId,DateTime? date)
        {

            CreateBookingViewModel model = new CreateBookingViewModel
            {
                TherapistsSelectListItems = GetTherapists(),
                TreatmentsSelectListItems = therapistId == null
                    ? GetTreatments()
                    : GetTreatments(therapistId.Value)
            };
            
            if (date == null)
            {
                date = DateTime.Today;
                model.date = date.Value;
            }

            model.WeekFreeTimes = new List<DayTimeSlotViewModel>();
            if (therapistId != null)
            {
                int week = CalendarService.GetWeekOfYear(date.Value);
                int year = date.Value.Year;
                DateTime firsDay = CalendarService.FirstDateOfWeekISO8601(year, week);
                IEnumerable<IEnumerable<ITimeSlot>> freeTimeSlotsForTherapist = factory.TimeSlotGateway.GetFreeTimeSlotsForTherapist(
                    therapistId.Value, week, year);
                for (int i = 0; i < 7; i++)
                {
                    DayTimeSlotViewModel dayTimeSlotViewModel = new DayTimeSlotViewModel();
                    dayTimeSlotViewModel.TimeSlots = new List<ITimeSlot>();
                    dayTimeSlotViewModel.Date = firsDay.AddDays(i);
                    dayTimeSlotViewModel.TimeSlots = freeTimeSlotsForTherapist.ElementAt(i).ToList();
                    model.WeekFreeTimes.Add(dayTimeSlotViewModel);
                }
            }
            else
            {
                for (int i = 0; i < 7; i++)
                {
                    DayTimeSlotViewModel dayTimeSlotViewModel = new DayTimeSlotViewModel();
                    dayTimeSlotViewModel.TimeSlots = new List<ITimeSlot>();
                    model.WeekFreeTimes.Add(dayTimeSlotViewModel);
                }
            }
            
                return View(model);
        
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult Create(CreateBookingViewModel model)
        {
            try
            {
                Booking booking = new Booking();
                booking.BookingDate = DateTime.Now;
                booking.DateTime = model.date
                    .AddHours(model.Time.Hour)
                    .AddMinutes(model.Time.Minute);

                booking.CustomerProfileId = User.Identity.GetUserId<int>();

                booking.TherapistId = model.therapistId;
                
                booking.Treatments = new List<Treatment>();
                foreach (int treatmendId in model.SelectedTreatmentsId)
                {
                    booking.Treatments.Add( factory.TreatmentGateway.GetOne(treatmendId));
                }

                factory.BookingGateway.CreateOne(booking);

                return RedirectToAction("Index",new { userId = User.Identity.GetUserId<int>()});
            }
            catch
            {
                return View();
            }
        }

       

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            factory.BookingGateway.Delete(id);
            return RedirectToAction("Index");
        }

       
        private SelectList GetTherapists()
        {
            var allTheras = factory.TherapistGateway.GetAll()
                        .Select(x =>
                                new SelectListItem()
                                {
                                    Value = x.Id.ToString(),
                                    Text = x.Name
                                });
            

            return new SelectList(allTheras, "Value", "Text");
        }

        private SelectList  GetTreatments()
        {
            var allTreatments = factory.TreatmentGateway.GetAll()
                .Select(t => new SelectListItem()
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                });

            return new SelectList(allTreatments,"Value","Text");
        }
        private SelectList GetTreatments(int therapistId)
        {
            var therapist = factory.TherapistGateway.GetOne(therapistId, "Treatments");
            var allTreatments = therapist.Treatments
                .Select(t => new SelectListItem()
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                });

            return new SelectList(allTreatments, "Value", "Text");
        }

        
    }
}

FeetClinic.WEB/Controllers/TreatmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BE.BE.Treatments;
using FeetClinic.WEB.ServiceGateway;
using BE.BE;
using FeetClinic.WEB.Models;

namespace FeetClinic.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class TreatmentController : Controller
    {
        private readonly ServiceGatewayFactory service;

        public TreatmentController()
        {
            service = new ServiceGatewayFactory();
        }
        [AllowAnonymous]
        // GET: Treatment
        public ActionResult Index(string treatmentType)
        {
            IEnumerable<Treatment> treat = service.TreatmentGateway.GetAll("TreatmentType");
            ViewBag.TypeList = new SelectList(
                    service.TreatmentTypeGateway.GetAll().OrderBy(tt => tt.Name)
                        .Select(tt => tt.Name));
            if (string.IsNullOrEmpty(treatmentType))
            {
                return View(treat);
            }
            else
            {
                return View(treat.Where(t => t.TreatmentType.Name == treatmentType));
            }
            
        }

        // GET: Treatment/Create
        public ActionResult Create()
        {
            var model = new TreatmentCreateViewModel
            {
                Therap = GetTherapists(),
                Types = GetTypes()
            };
            return View(model);
        }
        // POST: Treatment/Create
        [HttpPost]
        public ActionResult Create(TreatmentCreateViewModel model)
        {

            if (ModelState.IsValid)
            {
                List<Therapist> allThera = new List<Therapist>();
                foreach (int id in model.SelectedTherapistId)
                {
                    Therapist thera = service.TherapistGateway.GetOne(id);
                    allThera.Add(thera);
                }
                Treatment treatment = new Treatment
                {
                    Name = model.Name,
                    Description = model.Description,
                    Price = model.Price,
                    Duration = model.Duration,
                    TreatmentTypeId = model.SelectedTypeId,
                    Therapists = allThera
                };

                service.TreatmentGateway.CreateOne(treatment);
                return RedirectToAction("Index");
            }
            return View();

        }

        // GET: Treatment/Edit/5
        public ActionResult Edit(int id)
        {
            Treatment treat = service.TreatmentGateway.GetOne(id,"TreatmentType,Therapists");
            if (treat == null)
            {
                return HttpNotFound();
            }

            TreatmentEditViewModel model = new TreatmentEditViewModel();
            model.Id = treat.Id;
            model.Duration = treat.Duration;
            model.Description = treat.Description;
            model.Name = treat.Name;
            model.Price = treat.Price;
            model.Therap = GetTherapists(treat.Therapists);
            model.Types = GetTypes(treat.TreatmentType);
            model.SelectedTypeId = treat.TreatmentType.Id;
            
            return View(model);
        }

        // POST: Treatment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TreatmentEditViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Therapist> allThera = new List<Therapist>();
                    foreach (int therapistId in model.SelectedTherapistId)
                    {
                        Therapist thera = service.TherapistGateway.GetOne(therapistId);
                        allThera.Add(thera);
                    }
                    Treatment treatment = new Treatment
                    {
                        Id = id,
                        Name = model.Name,
                        Description = model.Description,
                        Price = model.Price,
                        Duration = model.Duration,
                        TreatmentTypeId = model.SelectedTypeId,
                        Therapists = allThera
                };
                    service.TreatmentGateway.Update(treatment);
                    return RedirectToAction("Index");
                }
                return View(model);
            }
            catch
            {
                return View(model);
            }
        }


        // GET: Treatment/Delete/5
        public ActionResult Delete(int id)
        {
           
            service.TreatmentGateway.Delete(id);
            return RedirectToAction("Index");
        }


        private IEnumerable<SelectListItem> GetTherapists()
        {
            return GetTherapists(new List<Therapist>());
        }

        private IEnumerable<SelectListItem> GetTherapists(List<Therapist> eksistingTherapists )
        {
            List<SelectListItem> therapistSelectList = new List<SelectListItem>();

            foreach (Therapist therapist in service.TherapistGateway.GetAll())
            {
                therapistSelectList.Add( new SelectListItem{
                    Text = therapist.Name,
                    Value = therapist.Id.ToString(),
                    Selected = (eksistingTherapists.Any(t=>t.Id == therapist.Id))
                });
            }
            return therapistSelectList;
        }


        private IEnumerable<SelectListItem> GetTypes(TreatmentType type)
        {
            List<SelectListItem> treatmentTypeSelectList = new List<SelectListItem>();

            foreach (TreatmentType treatmentType in service.TreatmentTypeGateway.GetAll())
            {
                treatmentTypeSelectList.Add(new SelectListItem
                {
                    Text = treatmentType.Name,
                    Value = treatmentType.Id.ToString(),
                    Selected = (type.Id == treatmentType.Id)
                });
            }
            return treatmentTypeSelectList;

        }
        private IEnumerable<SelectListItem> GetTypes()
        {
            return GetTypes(new TreatmentType());
        }
    }
}

FeetClinic.WEB/Controllers/TreatmentTypesController.cs
using BE.BE.Treatments;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BE.Interfaces;
using FeetClinic.WEB.ServiceGateway;

namespace FeetClinic.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class TreatmentTypesController : Controller
    {

        private readonly ServiceGatewayFactory service;

        
        public TreatmentTypesController()
        {
            service = new ServiceGatewayFactory();
        }
        
        // GET: TreatmentTypes
        public ActionResult Index()
        {
            IEnumerable<TreatmentType> types = service.TreatmentTypeGateway.GetAll();
            return View(types);
        }

        // GET: TreatmentTypes/Details/5
        public ActionResult Details(int id)
        {
            TreatmentType type = service.TreatmentTypeGateway.GetOne(id);

            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // GET: TreatmentTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TreatmentTypes/Create
        [HttpPost]
        public ActionResult Create(TreatmentType type)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    service.TreatmentTypeGateway.CreateOne(type);
                    return RedirectToAction("Index");
                }
                return View(type);
            }
            catch
            {
                return View();
            }
        }

        // GET: TreatmentTypes/Edit/5
        public ActionResult Edit(int id)
        {
            TreatmentType type = service.TreatmentTypeGateway.GetOne(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: TreatmentTypes/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TreatmentType type)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    service.TreatmentTypeGateway.Update(type);

                    return RedirectToAction("Index");
                }
                return View(type);
            }
            catch
            {
                return View();
            }
        }

        // GET: TreatmentTypes/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                service.TreatmentTypeGateway.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                TreatmentType type = service.TreatmentTypeGateway.GetOne(id);
                return View(type);
            }
            
        }
    }
}

FeetClinic.WEB/Views/Treatment/Create.cshtml
@model FeetClinic.WEB.Models.TreatmentCreateViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create new treatment</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedTherapistId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedTherapistId, Model.Therap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedTherapistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedTypeId, Model.Types, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.SelectedTypeId, "", new {@class = "text-danger"})
                @Html.ActionLink("Create new type","Create","TreatmentTypes",null,new{@class="btn btn-default btn-xs btn-primary"})
            </div>
            
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FeetClinic.WEB/Views/Treatment/Edit.cshtml
@model FeetClinic.WEB.Models.TreatmentEditViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        <div class="form-group ">
            @Html.LabelFor(model => model.SelectedTherapistId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedTherapistId, Model.Therap, new { htmlAttributes = new { @class = "form-control" }, size = 8, style = "width: 300px;" })
                @Html.ValidationMessageFor(model => model.SelectedTherapistId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedTypeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.SelectedTypeId, Model.Types, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SelectedTypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Duration, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Duration, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Duration, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FeetClinic.WEB/Views/Treatment/Index.cshtml
@model IEnumerable<BE.BE.Treatments.Treatment>

@{
    ViewBag.Title = "Treatments";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3> Alle behandlinger</h3>
    </div>
    <div class="panel-body">
        <div>
            <p>
                @using (Html.BeginForm("Index","Treatment",FormMethod.Get))
                {
                    @Html.DropDownList("treatmentType",
                    (SelectList) ViewBag.TypeList, "All",
                    new {onchange = "javascript:this.form.submit()"})
                }
                
            </p>
        </div>
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                @*<th class="text-right"> ID </th>*@
                <th class="text-center">Navn</th>
                <th class="text-left">Beskrivelse</th>
                <th class="text-center">Pris</th>
                <th class="text-center">Varighed</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var treatment in Model)
            {
                <tr>
                    @*<td class="text-right"> @treatment.Id</td>*@
                    <td>@Html.ActionLink(treatment.Name, "Edit", new {treatment.Id})</td>
                    <td class="text-left"> @treatment.Description</td>
                    <td class="text-center"> @treatment.Price.ToString("C")</td>
                    <td class="text-center"> @(treatment.Duration.Hours*60 + treatment.Duration.Minutes) min</td>
                    <td class="text-center">
                      @Html.ActionLink("Book","Create","Booking",null,new{@class="btn btn-default btn-xs btn-success"})
                      @using (Html.BeginForm("Delete", "Treatment"))
                        {
                            @Html.Hidden("id", treatment.Id)
                            <input type="submit" class="btn btn-default btn-xs btn-danger" value="Slet" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add new", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>