FeetClinic.WEB/Models/TherapistViewModels.cs
using BE.BE;
using BE.BE.Schedule;
using BE.BE.Treatments;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeetClinic.WEB.Models
{
    public class TherapistViewModel: CreateTherapistViewModel
    {
        public int Id { get; set; }
    }

    public class CreateTherapistViewModel
    {
        [Display(Name = "Treatments")]
        [Required(ErrorMessage = "Choose som treatments")]
        public int[] SelectedTreatmentId { get; set; }
        public IEnumerable<SelectListItem> TreatmentsSelectListItems { get; set; }

        [Required(ErrorMessage = "Enter the name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Enter description")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        public List<Treatment> Treatments { get; set; }
        public List<DayWorkingHours> WorkingHourses { get; set; }

    }

    

}

FeetClinic.WEB/Controllers/TherapistController.cs
using BE.BE;
using BE.BE.Treatments;
using FeetClinic.WEB.Models;
using FeetClinic.WEB.ServiceGateway;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FeetClinic.WEB.Controllers
{
    [Authorize(Roles = "admin")]
    public class TherapistController : Controller
    {
        private readonly ServiceGatewayFactory service;


        public TherapistController()
        {
            service = new ServiceGatewayFactory();
        }
        // GET: Therapist
        [AllowAnonymous]
        public ActionResult Index()
        {
            IEnumerable<Therapist> therapists = service.TherapistGateway.GetAll();
            return View(therapists);
        }

        // GET: Therapist/Create
        public ActionResult Create()
        {
            var model = new CreateTherapistViewModel()
            {
                TreatmentsSelectListItems = GetTreatmentForSelectedList(),
                
            };
            return View(model);
        }

        // POST: Therapist/Create
        [HttpPost]
        public ActionResult Create(CreateTherapistViewModel model)
        {

                if (ModelState.IsValid)
                {
                List<Treatment> treats = new List<Treatment>();
                    model.SelectedTreatmentId = model.SelectedTreatmentId ?? new int[0];
                foreach (int i in model.SelectedTreatmentId)
                    {
                        treats.Add(service.TreatmentGateway.GetOne(i));
                    }
                Therapist therapist = new Therapist
                {
                    Name = model.Name,
                    Description = model.Description,
                    WorkingHourses = model.WorkingHourses,
                    Treatments = treats
                };

                service.TherapistGateway.CreateOne(therapist);
                return RedirectToAction("Index");
                }
                return View();

        }
        [AllowAnonymous]
        // GET: Therapist/Edit/5
        public ActionResult Edit(int id)
        {
            Therapist therapist = service.TherapistGateway.GetOne(id, "Treatments,WorkingHourses");
            if (therapist == null)
            {
                return HttpNotFound();
            }

            CreateTherapistViewModel model = new TherapistViewModel()
            {
                Description = therapist.Description,
                Name = therapist.Name,
                TreatmentsSelectListItems = GetTreatmentForSelectedList(therapist.Treatments),
                WorkingHourses = therapist.WorkingHourses,
                Id = therapist.Id
            };

            return View(model);
        }

        // POST: Therapist/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, TherapistViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    List<Treatment> treats = new List<Treatment>();
                    model.SelectedTreatmentId = model.SelectedTreatmentId ?? new int[0];
                    foreach (int i in model.SelectedTreatmentId)
                    {
                        treats.Add(service.TreatmentGateway.GetOne(i));
                    }
                    Therapist therapist = new Therapist
                    {
                        Id = id,
                        Name = model.Name,
                        Description = model.Description,
                        Treatments = treats
                    };
                    service.TherapistGateway.Update(therapist);
                    return RedirectToAction("Index");

                }
                return Edit(id);
            }
            catch
            {
                return Edit(id);
            }
        }

        // GET: Therapist/Delete/5
        public ActionResult Delete(int id)
        {
            service.TherapistGateway.Delete(id);
            return RedirectToAction("Index");
        }

        private IEnumerable<SelectListItem> GetTreatmentForSelectedList()
        {
            return GetTreatmentForSelectedList(new List<Treatment>());
        }

        private IEnumerable<SelectListItem> GetTreatmentForSelectedList(List<Treatment> existing )
        {
            List<SelectListItem> treatmentsSelectList = new List<SelectListItem>();

            foreach (Treatment treatment in service.TreatmentGateway.GetAll())
            {
                treatmentsSelectList.Add(new SelectListItem
                {
                    Value   = treatment.Id.ToString(),
                    Text = treatment.Name,
                    Selected = existing.Any(t=>t.Id==treatment.Id)
                });
            }
            return treatmentsSelectList;
        }
    }
}

FeetClinic.WEB/Views/Therapist/Create.cshtml
@model FeetClinic.WEB.Models.CreateTherapistViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add new therapist</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <br>
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedTreatmentId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedTreatmentId, Model.TreatmentsSelectListItems, new { htmlAttributes = new { @class = "form-control" }, style = "width: 300px", size = 8 })
                @Html.ValidationMessageFor(model => model.SelectedTreatmentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WorkingHourses, htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.ValidationMessageFor(model => model.WorkingHourses, "", new { @class = "text-danger" })
            <div class="col-md-10">
                @Html.Partial("_WorkingHoursPartial")
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FeetClinic.WEB/Views/Therapist/Details.cshtml
@model BE.BE.Therapist

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Therapist</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Treatments)
        </dt>
        <dd>
              
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FeetClinic.WEB/Views/Therapist/Edit.cshtml
@model FeetClinic.WEB.Models.TherapistViewModel

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectedTreatmentId, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.ListBoxFor(m => m.SelectedTreatmentId, Model.TreatmentsSelectListItems,new {htmlAttributes = new {@class = "form-control"},size = 12, style = "width: 300px;" })
                @Html.ValidationMessageFor(model => model.SelectedTreatmentId, "", new {@class = "text-danger"})
            </div>
        </div>


        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FeetClinic.WEB/Views/Therapist/Index.cshtml
@model IEnumerable<BE.BE.Therapist>

@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3> Vores behandler</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-center">Navn</th>
                <th class="text-left">Beskrivelse</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var therapist in Model)
            {
                <tr>
                    <td class="text-left">@Html.ActionLink(therapist.Name, "Edit", new { therapist.Id })</td>
                    <td class="text-left"> @therapist.Description</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Therapist"))
                        {
                            @Html.Hidden("id", therapist.Id)
                            <input type="submit" class="btn btn-default btn-xs btn-danger" value="Slet" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Add new", "Create", null, new { @class = "btn btn-default" })
    </div>
</div>

FeetClinic.WEB/Views/Therapist/_WorkingHoursPartial.cshtml
<div>
    <table class="table table-striped table-condensed table-bordered">
        <thead>
        <tr class="text-center">
            <td></td>
            <td>Monday</td>
            <td>Tuesday</td>
            <td>Thursday</td>
            <td>Wednesday</td>
            <td>Friday</td>
            <td>Saturday</td>
            <td>Sunday</td>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <label>Start:</label>
            </td>
            @for (int i = 0; i < 7; i++)
            {
                <td><input type="time" name="WorkingHourses.[@i].StartTime" value="07:00"/></td>
            }
        </tr>
        <tr>
            <td>
                <label>End:</label>
            </td>
            @for (int i = 0; i < 7; i++)
            {
                <td><input type="time" name="WorkingHourses.[@i].EndTime" value="15:00"/></td>
            }
        </tr>
        <tr>
            <td>
                <label>StartLunch:</label>
            </td>
            @for (int i = 0; i < 7; i++)
            {
                <td><input type="time" name="WorkingHourses.[@i].StartLunch" value="11:30"/></td>
            }
        </tr>
            <tr>
                <td>
                    <label>LunchDuration:</label>
                </td>
                @for (int i = 0; i < 7; i++)
                {
                    <td><input name="WorkingHourses.[@i].LunchDuration" type="text" value="00:30:00" style="width: 75px"/></td>
                }
            </tr>
        </tbody>
    </table>


</div>